# In the name of Allah

"""Problems

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


number1 = 0   #First number
number2 = 1   #Second number
sum = 0       #Total sum value

while number2 < 4e6:     # 4e6 = 4000000
    number1, number2 = number2, number2 + number1    #Instant changing variables
    """ 
    Another way to changing variables

    temp = number1                
    number1 = number2             =========>>>>>>>>>  If we do not assign number1 to another variable like temp , number1 is gonna equal to new number1 
    number2 = number1 + temp
   
    """
    if number1 % 2 == 0:
        sum += number1

print(sum)    # Answer is 4613732
